//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUCrtProyectoLuis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CabezaFactura> CabezaFactura { get; set; }
        public virtual DbSet<Carrito> Carrito { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<CuerpoFactura> CuerpoFactura { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<ProductoEnCarrito> ProductoEnCarrito { get; set; }
        public virtual DbSet<Promocion> Promocion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<PestadosProductoPorCategoria_Result> PestadosProductoPorCategoria(string estado)
        {
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PestadosProductoPorCategoria_Result>("PestadosProductoPorCategoria", estadoParameter);
        }
    
        public virtual ObjectResult<PestadosProductoPorPromociones_Result> PestadosProductoPorPromociones(string estado)
        {
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PestadosProductoPorPromociones_Result>("PestadosProductoPorPromociones", estadoParameter);
        }
    
        public virtual ObjectResult<PventasPorMesesSegunCategoria_Result> PventasPorMesesSegunCategoria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PventasPorMesesSegunCategoria_Result>("PventasPorMesesSegunCategoria");
        }
    
        public virtual ObjectResult<PventasProductosExistentesPorcategoria_Result> PventasProductosExistentesPorcategoria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PventasProductosExistentesPorcategoria_Result>("PventasProductosExistentesPorcategoria");
        }
    }
}
